name: 'Sync Config Templates'
description: 'Sync configuration templates into a project and create a pull request if needed'
author: 'Thomas Schmelzer'

inputs:
  branch:
    description: 'Branch to sync changes to'
    default: 'sync/update-configs'
    required: false
  commit-message:
    description: 'Commit message for sync'
    default: 'chore: sync config files from .config-templates'
    required: false

runs:
  using: "composite"
  steps:
    - name: Copy sync script into workspace
      run: |
        cp "${{ github.action_path }}/scripts/up.sh" ./up.sh
        chmod +x ./up.sh
      shell: bash

    - name: Run config sync
      run: ./up.sh --yes
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: ${{ inputs.commit-message }}
        branch: ${{ inputs.branch }}
        title: ${{ inputs.commit-message }}
        body: |
          This PR updates config files from [tschm/.config-templates](https://github.com/tschm/.config-templates).
        delete-branch: true