name: 'Sync Config Templates'
description: 'Sync configuration templates into a project and create a pull request if needed'
author: 'Thomas Schmelzer'

inputs:
  branch:
    description: 'Branch to sync changes to'
    default: 'sync/update-configs'
    required: false
  commit-message:
    description: 'Commit message for sync'
    default: 'chore: sync config files from .config-templates'
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure Git repository
      run: |
        git rev-parse --is-inside-work-tree > /dev/null || {
          echo "❌ Not in a git repository"
          exit 1
        }
      shell: bash

    - name: Download and apply templates
      run: |
        set -euo pipefail

        REPO_URL="https://github.com/tschm/.config-templates"
        TEMP_DIR="$(mktemp -d)"
        trap 'rm -rf "$TEMP_DIR"' EXIT

        echo "📥 Downloading template archive..."
        curl -sSL -o templates.zip "$REPO_URL/archive/refs/heads/main.zip"

        echo "📦 Extracting..."
        unzip -q templates.zip -d "$TEMP_DIR"
        rm -f templates.zip

        EXTRACTED_DIR="${TEMP_DIR}/.config-templates-main"

        echo "🧹 Removing internal files..."
        rm -f "${EXTRACTED_DIR}/scripts/up.sh"
        rm -f "${EXTRACTED_DIR}/action.yml"

        echo "📂 Copying to working directory..."
        cp -Rf "${EXTRACTED_DIR}/." .

        echo "✅ Sync complete. Changed files:"
        git status --short || true
      shell: bash

    # Override the token for create-pull-request action using the PAT secret
    - name: Create Pull Request (override token)
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PAT_TOKEN }}          # Use PAT token here
        commit-message:
          chore: sync config files from .config-templates
        branch: sync/update-configs
        title:
          chore: sync config files from .config-templates
        body: |
          This PR updates config files from [tschm/.config-templates](https://github.com/tschm/.config-templates).
        delete-branch: true
