#name: 'Config Templates Updater'
#description: 'Downloads and extracts configuration templates from GitHub repository'
#author: 'Thomas Schmelzer'
#
#branding:
#  icon: 'download'
#  color: 'blue'
#
#inputs:
#  repository:
#    description: 'GitHub repository to download templates from'
#    required: false
#    default: 'tschm/.config-templates'
#  ref:
#    description: 'Branch or tag to download templates from'
#    required: false
#    default: 'v0.3.01'
#
#runs:
#  using: 'composite'
#  steps:
#    - name: Download templates
#      shell: bash
#      run: |
#        echo "Downloading templates from ${{ inputs.repository }}@${{ inputs.ref }}"
#        curl -L -o templates.zip https://github.com/${{ inputs.repository }}/archive/refs/tags/${{ inputs.ref }}.zip
#
#    - name: Extract templates
#      shell: bash
#      run: |
#        echo "Extracting templates"
#        unzip templates.zip
#
#    - name: Copy templates to current directory
#      shell: bash
#      run: |
#        echo "Copying templates to current directory"
#        cp -r $(echo "${{ inputs.repository }}" | cut -d '/' -f 2)-${{ inputs.ref }}/. .
#
#    - name: Clean up temporary files
#      shell: bash
#      run: |
#        echo "Cleaning up temporary files"
#        rm -rf templates.zip $(echo "${{ inputs.repository }}" | cut -d '/' -f 2)-${{ inputs.ref }}
