# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
# Workflow: Deptry
# Purpose: This workflow identifies missing and obsolete dependencies in the project.
#          It helps maintain a clean dependency tree by detecting unused packages and
#          implicit dependencies that should be explicitly declared.
name: "DEPTRY"

# Trigger: This workflow runs on every push and on pull requests to the main branch
on:
  push:
  pull_request:
    # Only run on pull requests targeting the main branch
    branches: [ main ]

# Permissions: Only read access to repository contents is needed
permissions:
    contents: read

jobs:
  check_pyproject:
    name: Check pyproject.toml presence
    runs-on: ubuntu-latest
    outputs:
      pyproject_exists: ${{ steps.setup.outputs.pyproject_exists }}
    steps:
      - uses: actions/checkout@v5

      # Use the composite action to setup the project and check for pyproject.toml
      - name: Setup the project
        id: setup
        uses: ./.github/actions/setup-project

  deptry_analysis:
    name: Run deptry if pyproject.toml exists
    needs: check_pyproject
    runs-on: ubuntu-latest
    if: needs.check_pyproject.outputs.pyproject_exists == 'true'
    steps:
      - uses: actions/checkout@v5

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run deptry
        run: task quality:deptry
