# Manual Release Workflow for Python Package using Hatch and
# Trusted Publisher (OIDC)
#
# This workflow implements a secure, maintainable release pipeline
# by separating concerns:
#   - 🔖 Tagging the release (Git tag)
#   - 🏗️ Building the package with Hatch
#   - 🚀 Publishing to PyPI using OIDC (no passwords or secrets)
#
# 🔐 Security:
#   - No PyPI credentials are stored; relies on Trusted Publishing via GitHub OIDC.
#
# 📄 Requirements:
#   - `pyproject.toml` with a top-level `version = "..."`
#   - Package is registered on PyPI as a Trusted Publisher with this repository
#
# ✅ To trigger:
#   - Go to the "Actions" tab
#   - Run this workflow manually with a tag input like `v1.2.3`

name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
        type: string

permissions:
  contents: write  # Needed to create releases

jobs:
  tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Git Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

  build:
    name: Build with Hatch
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history and tags available

      - name: Check if pyproject.toml exists
        id: check_file
        run: |
          if [ -f "pyproject.toml" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        if: steps.check_file.outputs.exists == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Hatch
        if: steps.check_file.outputs.exists == 'true'
        run: |
          pip install --upgrade pip
          pip install hatch

      - name: Set version from tag in pyproject.toml
        if: steps.check_file.outputs.exists == 'true'
        run: |
          version=${{ github.event.inputs.tag }}
          version=${version#v}
          echo "Setting version to $version"
          sed -i.bak "s/^version = .*/version = \"$version\"/" pyproject.toml
          rm pyproject.toml.bak

      - name: Build Package
        if: steps.check_file.outputs.exists == 'true'
        run: hatch build

      - name: Upload dist/
        if: steps.check_file.outputs.exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [tag, build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history and tags available

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
        continue-on-error: true  # Continue even if there are no artifacts (no pyproject.toml)

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if dist directory exists and has files
          if [ -d "dist" ] && [ "$(ls -A dist)" ]; then
            # Create release with assets
            gh release create ${{ github.event.inputs.tag }} \
              --title "${{ github.event.inputs.tag }}" \
              --generate-notes \
              dist/*
          else
            # Create release without assets
            gh release create ${{ github.event.inputs.tag }} \
              --title "${{ github.event.inputs.tag }}" \
              --generate-notes
          fi
