name: Release Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Needed to create releases

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the target repo
        uses: actions/checkout@v4

      - name: Sync config templates
        uses: tschm/.config-templates@main
        with:
          branch: sync/update-configs
          commit-message: sync config files from .config-templates
